# Use an official Node.js image as the base
FROM node:21-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available) first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the server code
COPY . .

# Expose the port the app runs on
EXPOSE ${PORT:-3000}

# Command to run the app
CMD ["npm", "run", "dev"]
