version: "3"

services:
  server:
    build:
      context: "."
      dockerfile: Dockerfile.local
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=local
      - PORT=${PORT:-3000}
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  node_modules:
